title: Sandip Koli
logo: /assets/img/sndipk.jpg
description: Im a data analyst with a passion for transforming data into valuable insights. Welcome to my GitHub profile, where youll find a collection of my data-driven projects and explorations.
show_downloads: true
theme: jekyll-theme-minimal

